<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/18 0018
 * Time: 下午 15:49
 */

namespace app\lib\exception;


use Exception;
use think\exception\Handle;

class ExceptionHandle extends Handle
{
    public $msg;
    public $status;

    public function render(Exception $e)
    {
        if($e instanceof BaseException){
            //是自定义异常
            $this->msg = $e->msg;
            $this->status = $e->status;
        }else{
            return parent::render($e); // TODO: Change the autogenerated stub
        }
        $result = [
            'msg' => $this->msg,
            'status' => $this->status
        ];
        return json($result);
    }
}